# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jeffnoxon/ubuntu-20.04-arm64"
  # config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = 'k8s-dev'
  config.vm.define vm_name = 'k8s'

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive

    #change the source.list
    sudo apt-get update
    sudo apt-get install -y vim git cmake build-essential tcpdump tig jq socat bash-completion yamllint shellcheck

    if ! command -v docker &> /dev/null; then
        # Install Docker
        export DOCKER_VERSION="5:20.10.16~3-0~ubuntu-jammy"

        # export DOCKER_VERSION="5:19.03.5~3-0~ubuntu-bionic"
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        # sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo add-apt-repository \
              "deb [arch=arm64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
        sudo apt-get update
        sudo apt-cache policy docker-ce
        sudo apt-get install -y docker-ce

        sudo usermod -aG docker $USER
    fi

    if [ ! -d ~/.bash_it ]
    then
      git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
      bash ~/.bash_it/install.sh -s
    fi

    #Disable swap
    #https://github.com/kubernetes/kubernetes/issues/53533
    sudo swapoff -a && sudo sysctl -w vm.swappiness=0
    sudo sed '/vagrant--vg-swap/d' -i /etc/fstab

    if [ ! -d ~/hiskio-course ]
    then
      git clone https://github.com/unknowntpo/hiskio-course.git
    fi

    if ! command -v kubectl &> /dev/null
    then
        echo "kubectl could not be found"
         # https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client

        echo 'source <(kubectl completion bash)' >> ~/.bashrc
        echo 'alias kc="kubectl"' >> ~/.bashrc
    fi

    if ! command -v kind &> /dev/null
    then
        echo "kind could not be found"

        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-arm64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

        sudo kind create cluster --config hiskio-course/vagrant/kind.yaml
        mkdir -p $HOME/.kube
        kind get kubeconfig > $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
    fi

    kubectl plugin list | grep "krew" -q
    if [ $? -ne 0 ]; then
        # Install krew
        set -x; cd "$(mktemp -d)" &&
        OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
        ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
        KREW="krew-${OS}_${ARCH}" &&
        curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
        tar zxvf "${KREW}.tar.gz" &&
        ./"${KREW}" install krew
        echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' >> ~/.bashrc
    fi
  SHELL

  config.vm.network :private_network, ip: "172.17.8.111"
  config.vm.provider "parallels" do |v|
    v.memory = 8192
    v.cpus = 4
  end
end
